[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish -c Release --output /app/out"]

[start]
cmd = "dotnet /app/out/game-store.dll"
