// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using game_store.Data;

#nullable disable

namespace game_store.Migrations
{
    [DbContext(typeof(GameStoreDbContext))]
    partial class GameStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("game_store.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CD Projekt Red"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FromSoftware"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rockstar Games"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Studio MDHR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toys for Bob"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ConcernedApe"
                        });
                });

            modelBuilder.Entity("game_store.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platforms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardImageUrl = "https://res.cloudinary.com/dcbkiur84/image/upload/v1782507807/new-witcher-wild-hunt-logo-v0-gCzbZVZx31hdPm1UN36U98kVIptlR_lLDLYXmEV1QXU_oscoju.webp",
                            CompanyId = 1,
                            CoverImageUrl = "https://res.cloudinary.com/dcbkiur84/image/upload/v1782505011/kh4MUIuMmHlktOHar3lVl6rY_pwtvx4.jpg",
                            Description = "An open-world action RPG set in a dark fantasy universe.",
                            GenreId = 1,
                            IsAvailable = true,
                            Name = "The Witcher 3: Wild Hunt",
                            Platforms = "[0]",
                            Price = 39.99m,
                            ReleaseDate = new DateOnly(2015, 5, 19)
                        },
                        new
                        {
                            Id = 2,
                            CardImageUrl = "https://res.cloudinary.com/dcbkiur84/image/upload/v1782508043/EGS_Cyberpunk2077_CDPROJEKTRED_S1_03_2560x1440-359e77d3cd0a40aebf3bbc130d14c5c7_lujx3a.jpg",
                            CompanyId = 1,
                            CoverImageUrl = "https://res.cloudinary.com/dcbkiur84/image/upload/v1782508043/EGS_Cyberpunk2077_CDPROJEKTRED_S1_03_2560x1440-359e77d3cd0a40aebf3bbc130d14c5c7_lujx3a.jpg",
                            Description = "A futuristic open-world RPG set in Night City.",
                            GenreId = 1,
                            IsAvailable = true,
                            Name = "Cyberpunk 2077",
                            Platforms = "[0,1]",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2020, 12, 10)
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            CoverImageUrl = "https://example.com/images/eldenring.jpg",
                            Description = "Explore the Lands Between in this epic action RPG.",
                            GenreId = 1,
                            IsAvailable = true,
                            Name = "Elden Ring",
                            Platforms = "[1,2]",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2022, 2, 25)
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 4,
                            CardImageUrl = "https://res.cloudinary.com/dcbkiur84/image/upload/v1782567890/apps.58691.13670972585585116.3e5032b0-0174-4e7d-b3ed-55f9306df6f1_nvylrq.jpg",
                            CoverImageUrl = "https://res.cloudinary.com/dcbkiur84/image/upload/v1782567898/Cuphead_capa_sqc05m.png",
                            Description = "A run-and-gun indie game with hand-drawn 1930s cartoon art style.",
                            GenreId = 2,
                            IsAvailable = true,
                            Name = "Cuphead",
                            Platforms = "[0,2,3]",
                            Price = 19.99m,
                            ReleaseDate = new DateOnly(2017, 9, 29)
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 5,
                            CoverImageUrl = "https://example.com/images/crash4.jpg",
                            Description = "A brand new Crash Bandicoot adventure with classic platforming action.",
                            GenreId = 3,
                            IsAvailable = true,
                            Name = "Crash Bandicoot 4: It's About Time",
                            Platforms = "[0,1,2,3]",
                            Price = 39.99m,
                            ReleaseDate = new DateOnly(2020, 10, 2)
                        },
                        new
                        {
                            Id = 6,
                            CardImageUrl = "https://res.cloudinary.com/dcbkiur84/image/upload/v1782568319/gta-vi_mkgvim.jpg",
                            CompanyId = 3,
                            CoverImageUrl = "https://res.cloudinary.com/dcbkiur84/image/upload/v1782568287/grand-theft-auto-vi_8stb_mbvxrc.jpg",
                            Description = "The next entry in the Grand Theft Auto series, coming to modern consoles.",
                            GenreId = 2,
                            IsAvailable = false,
                            Name = "GTA VI",
                            Platforms = "[1,2]",
                            Price = 69.99m,
                            ReleaseDate = new DateOnly(2025, 9, 30)
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 6,
                            CoverImageUrl = "https://example.com/images/stardew.jpg",
                            Description = "A farming simulation RPG set in a charming rural world.",
                            GenreId = 1,
                            IsAvailable = true,
                            Name = "Stardew Valley",
                            Platforms = "[0,3]",
                            Price = 14.99m,
                            ReleaseDate = new DateOnly(2016, 2, 26)
                        });
                });

            modelBuilder.Entity("game_store.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("game_store.Models.Game", b =>
                {
                    b.HasOne("game_store.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("game_store.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
